openapi: 3.1.0
info:
  title: Nancy Slack-RAG Bridge
  version: "0.2.0"
servers:
  - url: https://nancy-brain.malpas.nz
components:
  schemas: {}
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
paths:
  /search:
    get:
      operationId: searchDocs
      summary: SEARCH <query> limit n
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 6
            maximum: 12
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hits:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        score:
                          type: number
                        text:
                          type: string
                        source_document:
                          type: string
                        line_start:
                          type: integer
                        line_end:
                          type: integer
                        chunk_index:
                          type: integer
                        chunk_count:
                          type: integer
                  index_version:
                    type: string
                  trace_id:
                    type: string
  /retrieve:
    post:
      operationId: retrieveFile
      summary: RETRIEVE <file_path>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doc_id:
                  type: string
                start:
                  type: integer
                  description: 1-based line start (inclusive)
                end:
                  type: integer
                  description: 1-based line end (inclusive)
                window:
                  type: integer
                  description: Chunk window size for chunk ids
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  passage:
                    type: object
                    properties:
                      doc_id:
                        type: string
                      text:
                        type: string
                      github_url:
                        type: string
                      content_sha256:
                        type: string
                      start:
                        type: integer
                      end:
                        type: integer
                      total_lines:
                        type: integer
                      mode:
                        type: string
                      chunks:
                        type: array
                        items:
                          type: object
                  trace_id:
                    type: string
  /tree:
    get:
      operationId: listTree
      summary: TREE <dir>
      parameters:
        - in: query
          name: prefix
          required: false
          schema:
            type: string
        - in: query
          name: depth
          required: false
          schema:
            type: integer
            default: 2
        - in: query
          name: max_entries
          required: false
          schema:
            type: integer
            default: 500
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      type: object
                      properties:
                        path:
                          type: string
                        type:
                          type: string
                          enum: [file, dir]
  /weight:
    post:
      operationId: setWeight
      summary: WEIGHT <file_path, multiplier>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                multiplier:
                  type: number
                  minimum: 0.5
                  maximum: 2.0
      responses:
        "200":
          description: OK
